console.log("----dasar javascript----")
console.log(12+3);
console.log(0.3 + 0.7);
console.log(0.1 + 0.2);
console.log(-25)
console.log("jangan pernah mengawali angka 0 diawal")
console.log("bilangan oktal 022 : " + 022)
console.log("bilangan hexadecimal 0xFF :" + 0xFF)
console.log("angka special 2/0 : " + 2/0)
console.log("angka special -2/0 : " + -2/0)
console.log("angka special 0/0 : " + 0/0)
console.log("angka special 100/'apel' :" + 100/"apel")
console.log("----------------------")
console.log("----operator pada javascript----")
console.log("operator aritmatika")
console.log("+ , - , * , / , %")
console.log(5+10)
console.log("sisa pembagian dari 10 dibagi 5 (10 bagi 5 sama dengan 2 sisa baginya 0) : " + 10 % 5)
console.log("")
console.log("operator predence : KuBaTaKu () , * , / , + , -")
console.log(1 + 2 * 3 - 4)
console.log("")
console.log("opertor penugasan : = ")
console.log("var a = 10")
var a = 10
console.log(a)
var x = 15
y = 10
console.log("var x = 15; y = 10")
console.log("x += y | x -= y | x *= y | x /= y | x %= y")
console.log(x += y , x -= y , x *= y , x /= y , x %= y)
console.log("")
console.log("Operator Perbandingan")
console.log("sama dengan == : (10 == 10 , 10 == 5) hasilnya : " + (10 == 10) + " , " + (10 == 5));
console.log("tidak sama dengan != : (10 != 10) , (10 != 5) hasilnya : " + (10 != 10) + " , " + (10 != 5))
console.log("operator strict digunakan ketika pembandingnya bertipe string")
console.log("strict sama dengan === : (10 == '10') , (10 === '10') hasilnya : " + (10 == '10') + " , " + (10 === '10'))
console.log("")
console.log("Operator Logika")
console.log("berfungsi menggabungkan dua buah operator")
console.log("jenis Operator Logika : && = AND , || = OR , ! = NOT")
console.log("AND : jika salah satu bernilai false maka akan hasil operasinya false,keduanya harus true")
console.log("OR : jika salah satu bernilai true hasil operasinya pasti true")
console.log("NOT : membalikan nilai aslinya, misal hasil operasinya true maka dibalikan menjadi false")
console.log("contoh AND (var x = 19, (x % 2 == 1) && (x > 10))")
console.log("contoh OR (var z = 20, (x % 2 == 1) || (z < 10))")
console.log("contoh NOT (var x = 19, !(n > 10))")
console.log("artinya cek bilangan ganjil dan apakah lebih dari 10")
var x = 19;
var z = 20;
console.log((x % 2 == 1) && (x > 10))
console.log((z % 2 == 1) || (z < 10))
console.log(!(x > 10) + " , seharusnya true dibalikan jadi false")
console.log("")
console.log("Operator String")
console.log('10 + "10" = ' , 10 + "10")
console.log('"10" + 10 = ' , "10" + 10)
console.log('10 + 10 + "10" = ' , 10 + 10 + "10")
console.log('"10" + 10 + 10 = ' , "10" + 10 + 10)
console.log("jika didepannya string data selanjutnya akan dianggap string")
console.log("")
console.log("Operator TypeOf")
console.log("syntax : typeof(operand)")
console.log("typeof(10) , typeof('10') , typeof(true) contoh = " , typeof(10) , typeof('10') , typeof(true))
console.log("")
console.log("Operator Kondisional")
console.log("syntax : (kondisi) ? bener : salah")
console.log("contoh : var x = 19; (x % 2 == 0) ? 'genap' : 'salah' , hasilnya = " , (x % 2 == 0 ) ? "genap" : "ganjil")
console.log("----------------------------")
console.log("Tipe Data String")
console.log("Escape Character : Lihat di ss html")
console.log("menghitung panjang string = 'Sandhika Galih'.length hasilnya = " , "Sandhika Galih".length)
console.log("----------------------------")